apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server-app
  template:
    metadata:
      labels:
        app: chat-server-app
    spec:
      containers:
      - name: chat-server-app
        image: simplechat:latest
        ports:
        - containerPort: 32000
    
---

apiVersion: v1
kind: Service
metadata:
  name: chat-server-app-service
spec:
  type: LoadBalancer
  selector:
    app: chat-server-app
  ports:
  - port: 32000
    nodePort: 32000
    targetPort: 32000
