apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-app
spec:
  selector:
    matchLabels:
      app: chat-server-app
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: chat-server-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: chat-server-app
        image: jfsilvapt/chat-server-app:v1.3.0
        ports:
        - containerPort: 32000
        
---

apiVersion: v1
kind: Service
metadata:
  name: chat-server-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: chat-server-app
  ports:
  - port: 32000
    targetPort: 32000
    nodePort: 32000



