apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server-app
  template:
    metadata:
      labels:
        app: chat-server-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: chat-server-app
        image: simplechatproj.azurecr.io/chat-server-app:v1.0.0       
        env:
        - name: "PORT"
    
---

apiVersion: v1
kind: Service
metadata:
  name: chat-server-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: chat-server-app
  ports:
  - port: 8080
    targetPort: 5555
    nodePort: 30003


