name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - name: Create tag artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}
          path: Release
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_HUB_AT }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_ID }}/simplechat:latest
            ${{ secrets.DOCKER_ID }}/simplechat:${{github.ref_name}}
